### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by gzhang91** [panekj/lapce-cpp-clangd#2]
i had install this plugin in windows, and also install llvm, but i cannot get any effect about it, i cannot jump over source code

**Comment by LeFoenk** [comment]
Open CMD and type "clangd --version"

It should display the clangd version you have installed.
If it doesn´t find your clangd.exe, add its folder to "Path" : [https://stackoverflow.com/questions/44272416/how-to-add-a-folder-to-path-environment-variable-in-windows-10-with-screensho](https://stackoverflow.com/questions/44272416/how-to-add-a-folder-to-path-environment-variable-in-windows-10-with-screensho)



Open your settings.toml and paste this:

```
[lapce-cpp-clangd.volt]
clangdVersion = "15.0.1" # git tag from https://github.com/clangd/clangd
serverPath = "clangd.exe"
serverArgs = [
    #custom args
]
```
replace 15.0.1 with your version of clangd

You might need to retstart lapce, idk.

I think ive read somewhere that the current binary from the website has a bug, so maybe you also need to build lapce from source.

**Comment by panekj** [comment]
it's not ready to be used
