### ISSUE TITLE
clangd file is universal on mac

### ISSUE THREAD

**Issue by gdamore** [panekj/lapce-cpp-clangd#3]
There isn't a good reason to restrict this from working on macOS M1 ARM.

The downloaded binaries for clangd are universal (meaning they work on both ARM and x86) -- even if they weren't, x86 binaries would Just Work.

In fact, on windows, the same situation prevails -- Windows supports x86 binaries running on their ARM variants just fine, at least on Windows 11.

Linux is the only outlier here.  (It's too bad clangd doesn't supply ARM binaries.)

**Comment by gdamore** [comment]
You closed this, but I don't see an associated commit?  I had a branch that I was going to submit as a PR, but ... ?

**Comment by Elara6331** [comment]
You can run x86 binaries on ARM linux as well if you install `qemu-user-static`, but regardless, you can just install it using your package manager and then provide the path in the settings.
