### ISSUE TITLE
Issue on MacOs (Arm)

### ISSUE THREAD

**Issue by NicolasGermann** [panekj/lapce-cpp-clangd#5]
Clangd not working, (no such file or directory (os error 44)).
Supplying path to native clangd installation does not help.

**Comment by D-T-666** [comment]
I am getting this:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/35934791/208254141-9c8f0900-f48e-404e-9088-faa8eced3779.png">

**Comment by panekj** [comment]
Should be fixed now
