### ISSUE TITLE
Failed to find a pre-opened file descriptor through which ".clangd_ver" could be opened

### ISSUE THREAD

**Issue by leggettc18** [panekj/lapce-cpp-clangd#6]
I installed Lapce recently and went to install this plugin. I get this error when opening Lapce afterwards. I was able to make this error not appear by manually installing clangd from apt (14.0.0-1ubuntu1 in my case) and manually setting the version and path in settings.toml, but it still does not seem to actually do anything.

**Comment by leggettc18** [comment]
It turns out the latter issue of it not doing anything is only present in the Flatpak version. The .tar.gz version from the website still does show this error, but specifying the version and path in settings.toml does at least seem to make it actually work.

**Comment by Andre-LA** [comment]
Same here, I'm on `Fedora 37 (Workstation)`, running from flatpak doesn't work, but from the `tar.gz` works as described.

**Comment by nbonfire** [comment]
just curious, have you tried using flatseal to give it more permission

**Comment by panekj** [comment]
Fixed
