### ISSUE TITLE
Clangd server path needs to be explicitly stated in the config

### ISSUE THREAD

**Issue by hakro** [panekj/lapce-cpp-clangd#8]
Hi,

It seems that the ServerPath config needs to be specifically filled in the config of this plugin, with the absolute path for the clangd binary.

This is the case, even if clangd is present in one of the $PATH directories, and executes just fine when typing `clangd` in the terminal, without having to type the full absolute path.

Would it be possible to have Lapce use Clangd from the path by leaving the config empty ?

Cheers !

**Comment by panekj** [comment]
> It seems that the ServerPath config needs to be specifically filled in the config of this plugin, with the absolute path for the clangd binary.

Not correct. It can be relative or just binary name.



> Would it be possible to have Lapce use Clangd from the path by leaving the config empty ?

I don't see any reason to do that.

**Comment by hakro** [comment]
Thx.
I might have missed something when I was testing just with the binary name, but it works indeed.
Closing this
