### ISSUE TITLE
failed to find a pre-opened file descriptor which "clangd-windows-15.0.6.zip" could be opened

### ISSUE THREAD

**Issue by HojdaAdelin** [panekj/lapce-cpp-clangd#9]
This issue persist on Win 11.

**Comment by edgarogh** [comment]
Same issue on Linux Mint 21.1, Lapce is completely unusable due to this.

**Comment by edgarogh** [comment]
Seems like this only occurs when working on a remote SSH server for me.

**Comment by JeffofBread** [comment]
Issue for me on W10 version 21H2 build 19044.3086.

**Comment by chnoblouch** [comment]
My workaround for this was installing clangd manually using the [LLVM installer](https://github.com/llvm/llvm-project/releases), setting "Path to clangd" in the plugin settings and reloading the plugin.

**Comment by JeffofBread** [comment]
Tried and still kept giving me the same error.

**Comment by loxdogs** [comment]
still persist archlinux

**Comment by HojdaAdelin** [comment]
I think this error occure because of the path that the extension look for. But still if I set the path to the clang in the settings while I downloaded manually with LLVM the extension doesn't work. I think is better to move on VS Code or VS :))

**Comment by tomvictor** [comment]
<img width="403" alt="Screenshot 2023-09-12 at 16 00 48" src="https://github.com/lapce-community/lapce-cpp-clangd/assets/14200125/d9846c3f-f790-4ae7-aee2-82a01473eb5d">

Same issue on mac os (aarch64)

**Comment by tomvictor** [comment]
I managed to fix this by updating the toml file with the clangd path from > echo $PATH

**Comment by panekj** [comment]
This should be fixed now
